-- ==========================
-- EXEMPLOS DE SQL - RESUMO P1
-- ==========================

-- 1. DROP TABLE (com CASCADE CONSTRAINTS)
DROP TABLE CONSULTA CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE ESPECIALIDADE CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;

-- 2. CREATE TABLE com PRIMARY KEY, UNIQUE, CHECK, FOREIGN KEY
CREATE TABLE ESPECIALIDADE(
ID_ESP NUMBER(10) PRIMARY KEY,
NOME VARCHAR2(120) NOT NULL,
CONSTRAINT UQ_ESP_NOME UNIQUE (NOME)
);

CREATE TABLE PACIENTE(
ID_PAC NUMBER(10) PRIMARY KEY,
NOME VARCHAR2(240) NOT NULL,
DATA_NASC DATE NOT NULL,
GENERO CHAR(1) NOT NULL,
CPF CHAR(14),
CONSTRAINT CK_GENERO_PAC CHECK (GENERO IN ('M', 'F')),
CONSTRAINT UQ_PAC_CPF UNIQUE (CPF)
);

CREATE TABLE MEDICO(
CRM NUMBER(7) PRIMARY KEY,
NOME VARCHAR2(240) NOT NULL,
DATA_NASC DATE NOT NULL,
GENERO CHAR(1) NOT NULL,
ID_ESP NUMBER(10),
CONSTRAINT CK_MED_GENERO CHECK (GENERO IN ('M', 'F')),
CONSTRAINT FK_MED_ESP FOREIGN KEY (ID_ESP)
REFERENCES ESPECIALIDADE (ID_ESP)
);

CREATE TABLE CONSULTA(
CRM NUMBER(7),
ID_PAC NUMBER(10),
DTH_AGENDAMENTO DATE NOT NULL,
TIPO CHAR(1) NOT NULL,
STATUS CHAR(1) NOT NULL,
OBSERVACAO VARCHAR2(512),
CONSTRAINT PK_CONSULTA PRIMARY KEY(CRM, ID_PAC, DTH_AGENDAMENTO),
CONSTRAINT FK_CON_MED FOREIGN KEY (CRM)
REFERENCES MEDICO (CRM),
CONSTRAINT FK_CON_PAC FOREIGN KEY (ID_PAC)
REFERENCES PACIENTE (ID_PAC),
CONSTRAINT CK_CON_TIPO CHECK (TIPO IN ('C', 'R')),
CONSTRAINT CK_CON_STATUS CHECK (STATUS IN ('A', 'C', 'R'))
);

-- 3. SEQUENCES
CREATE SEQUENCE SEQ_PACIENTE
START WITH 1
MAXVALUE 9999999999 INCREMENT BY 1
NOCYCLE NOCACHE;

CREATE SEQUENCE SEQ_ESPECIALIDADE
START WITH 10
MAXVALUE 9999 INCREMENT BY 10
NOCYCLE NOCACHE;

-- 4. INSERT
INSERT INTO ESPECIALIDADE(ID_ESP, NOME)
VALUES(SEQ_ESPECIALIDADE.NEXTVAL, 'Cardiologista');

INSERT INTO PACIENTE(ID_PAC, NOME, DATA_NASC, GENERO, CPF)
VALUES(SEQ_PACIENTE.NEXTVAL, 'Ana Laura', TO_DATE('30/01/2003', 'DD/MM/YYYY'), 'F', '111.111.111-11');

INSERT INTO MEDICO (CRM, NOME, DATA_NASC, GENERO, ID_ESP)
VALUES (10111, 'Carlos Eduardo', TO_DATE('10/09/1951', 'DD/MM/YYYY'), 'M', SEQ_ESPECIALIDADE.CURRVAL);

INSERT INTO CONSULTA (CRM, ID_PAC, DTH_AGENDAMENTO, TIPO, STATUS, OBSERVACAO)
VALUES(10111, 1, TO_DATE('01/09/2025', 'DD/MM/YYYY'), 'C', 'A', 'Primeira consulta do paciente.');

COMMIT;

-- 5. SELECT
SELECT ID_PAC, NOME, TO_CHAR(DATA_NASC, 'DD/MM/YYYY') AS DATA_NASCIMENTO
FROM PACIENTE;

-- SELECT com JOIN (INNER e LEFT)
SELECT M.NOME AS MEDICO, E.NOME AS ESPECIALIDADE, P.NOME AS PACIENTE, C.DTH_AGENDAMENTO
FROM CONSULTA C
INNER JOIN MEDICO M ON C.CRM = M.CRM
LEFT JOIN ESPECIALIDADE E ON M.ID_ESP = E.ID_ESP
INNER JOIN PACIENTE P ON C.ID_PAC = P.ID_PAC;

-- 6. UPDATE
UPDATE PACIENTE
SET NOME = 'Ana Laura Santos', CPF = '222.222.222-22'
WHERE ID_PAC = 1;

-- 7. DELETE
DELETE FROM CONSULTA WHERE STATUS = 'C';

-- 8. ROLLBACK e COMMIT
ROLLBACK; -- Desfaz alterações não confirmadas
COMMIT;   -- Confirma permanentemente as alterações