-- ==========================
-- EXEMPLOS DE SQL - RESUMO P2
-- Conteúdos: JOINS, UNION, INDEX, VIEW
-- ==========================

-- 1.1 INNER JOIN - Funcionários e Cargos
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, J.JOB_TITLE
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID = J.JOB_ID;

-- 1.2 LEFT JOIN - Funcionários e Departamentos (traz todos os funcionários)
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 1.3 RIGHT JOIN - Departamentos e Funcionários (traz todos os departamentos)
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 1.4 FULL OUTER JOIN - Une tudo dos dois lados
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
FULL OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 1.5 CROSS JOIN - Produto cartesiano (evite usar sem necessidade)
SELECT C.NOME AS CLIENTE, P.NOME AS PRODUTO
FROM Cliente C
CROSS JOIN Produto P;

-- 1.6 JOIN com 3 tabelas
SELECT E.FIRST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN JOBS J ON E.JOB_ID = J.JOB_ID
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 1.7 JOIN N:N - Produto x Categoria
SELECT PR.NOME AS PRODUTO, C.NOME_CATEGORIA
FROM Produto PR
INNER JOIN Produto_Categoria PC ON PR.ID_PRODUTO = PC.ID_PRODUTO
INNER JOIN Categoria C ON PC.ID_CATEGORIA = C.ID_CATEGORIA;

-- 1.8 JOIN Pedido + Cliente
SELECT P.ID_PEDIDO, C.NOME, P.DATA_PEDIDO, P.VALOR_TOTAL
FROM Pedido P
INNER JOIN Cliente C
ON P.ID_CLIENTE = C.ID_CLIENTE;

-- 1.9 Pedido completo com Item_Pedido
SELECT P.ID_PEDIDO, PR.NOME AS PRODUTO, I.QUANTIDADE, I.SUBTOTAL
FROM Pedido P
INNER JOIN Item_Pedido I ON P.ID_PEDIDO = I.ID_PEDIDO
INNER JOIN Produto PR ON I.ID_PRODUTO = PR.ID_PRODUTO;

-- 2.1 UNION - Remove duplicatas
SELECT FIRST_NAME AS NOME FROM EMPLOYEES
UNION
SELECT NOME FROM CLIENTE;

-- 2.2 UNION ALL - Mantém duplicatas
SELECT FIRST_NAME AS NOME FROM EMPLOYEES
UNION ALL
SELECT NOME FROM CLIENTE;

-- 2.3 UNION combinando categorias e produtos
SELECT NOME_CATEGORIA AS DESCRICAO FROM Categoria
UNION
SELECT NOME FROM Produto;

-- 3.1 INDEX simples (melhora pesquisas pelo CPF)
CREATE INDEX IDX_CLIENTE_CPF
ON Cliente(cpf);

-- 3.2 INDEX UNIQUE
CREATE UNIQUE INDEX IDX_EMAIL_UNICO
ON Cliente(email);

-- 3.3 INDEX COMPOSTO (2 colunas)
CREATE INDEX IDX_PEDIDO_DATA_CLIENTE
ON Pedido(id_cliente, data_pedido);

-- 3.4 Remover INDEX
-- DROP INDEX IDX_CLIENTE_CPF;

-- 4.1 VIEW simples
CREATE OR REPLACE VIEW VW_FUNCIONARIOS AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;

-- 4.2 VIEW com JOIN
CREATE OR REPLACE VIEW VW_FUNC_DEPT AS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 4.3 VIEW com filtro
CREATE OR REPLACE VIEW VW_PRODUTOS_CAROS AS
SELECT ID_PRODUTO, NOME, PRECO
FROM Produto
WHERE PRECO > 100;

-- 4.4 VIEW de pedido completo
CREATE OR REPLACE VIEW VW_PEDIDO_COMPLETO AS
SELECT P.ID_PEDIDO, C.NOME AS CLIENTE,
       PR.NOME AS PRODUTO, I.QUANTIDADE, I.SUBTOTAL
FROM Pedido P
INNER JOIN Cliente C ON P.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN Item_Pedido I ON P.ID_PEDIDO = I.ID_PEDIDO
INNER JOIN Produto PR ON I.ID_PRODUTO = PR.ID_PRODUTO;