DROP TABLE PESSOA;

CREATE TABLE PESSOA (
    ID NUMBER(5) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    SALARIO NUMBER(10, 2) NOT NULL
);

ALTER TABLE PESSOA ADD EMAIL VARCHAR2(240);

INSERT INTO PESSOA (ID, NOME, SALARIO, EMAIL) 
VALUES (1, 'Maria', 1000, 'maria@email.com');
COMMIT;

SELECT * FROM PESSOA;

CREATE OR REPLACE PROCEDURE PROC_AUMENTAR_SALARIO (
    P_ID         IN  PESSOA.ID%TYPE,
    P_PERCENTUAL IN  NUMBER,
    P_SAIDA      OUT NUMBER
)
IS
    V_SALARIO      PESSOA.SALARIO%TYPE;
    V_NOVO_SALARIO PESSOA.SALARIO%TYPE;
BEGIN
    IF P_PERCENTUAL <= 0 OR P_PERCENTUAL >= 10 THEN
        P_SAIDA := -998;
        RETURN;
    END IF;

    BEGIN
        SELECT SALARIO
          INTO V_SALARIO
          FROM PESSOA
         WHERE ID = P_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_SAIDA := -999;
            RETURN;
    END;

    V_NOVO_SALARIO := V_SALARIO + (V_SALARIO * P_PERCENTUAL / 100);

    IF V_SALARIO >= 10000 OR V_NOVO_SALARIO > 10000 THEN
        P_SAIDA := -997;
        RETURN;
    END IF;

    UPDATE PESSOA
       SET SALARIO = V_NOVO_SALARIO
     WHERE ID = P_ID;

    P_SAIDA := 0;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_SAIDA := SQLCODE;
END;
/

-- Executar procedure
DECLARE
    RET NUMBER;
BEGIN
    PROC_AUMENTAR_SALARIO(1, 10, RET);
    DBMS_OUTPUT.PUT_LINE('Retorno: ' || RET);
END;

-- Verificar aumento 10%

SELECT * FROM PESSOA;

-- Passando procedure em function
CREATE OR REPLACE FUNCTION FUNC_AUMENTAR_SALARIO (
    P_ID          IN  PESSOA.ID%TYPE,
    P_PERCENTUAL  IN  NUMBER,
    P_SAIDA       OUT NUMBER
) RETURN NUMBER
IS
    V_SALARIO      PESSOA.SALARIO%TYPE;
    V_NOVO_SALARIO PESSOA.SALARIO%TYPE;
    V_RET          NUMBER(5);
BEGIN
    IF P_PERCENTUAL <= 0 OR P_PERCENTUAL >= 10 THEN
        V_RET := -998;
        P_SAIDA := V_RET;
        RETURN V_RET;
    END IF;

    BEGIN
        SELECT SALARIO
          INTO V_SALARIO
          FROM PESSOA
         WHERE ID = P_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_RET := -999;
            P_SAIDA := V_RET;
            RETURN V_RET;
    END;

    V_NOVO_SALARIO := V_SALARIO + (V_SALARIO * P_PERCENTUAL / 100);

    IF V_SALARIO >= 10000 OR V_NOVO_SALARIO > 10000 THEN
        V_RET := -997;
        P_SAIDA := V_RET;
        RETURN V_RET;
    END IF;

    UPDATE PESSOA
       SET SALARIO = V_NOVO_SALARIO
     WHERE ID = P_ID;

    V_RET := 0;
    P_SAIDA := V_RET;

    RETURN V_RET;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        V_RET := SQLCODE;
        P_SAIDA := V_RET;
        RETURN V_RET;
END;
/

-- Executar function
DECLARE
    RET NUMBER;
BEGIN
    RET := FUNC_AUMENTAR_SALARIO(1, 10, RET);
    DBMS_OUTPUT.PUT_LINE('Retorno: ' || RET);
END;

-- Cursor
DECLARE
    V_IDDEPT NUMBER(3);
BEGIN
    V_IDDEPT := 60;

    FOR RS IN (
        SELECT EMPLOYEE_ID, FIRST_NAME NOME, LAST_NAME AS SOBRENOME, SALARY,
               SALARY * 2 SALARIO_MULTIPLICADO
          FROM EMPLOYEES
         WHERE DEPARTMENT_ID = V_IDDEPT
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE('NOME DO FUNCIONARIO: ' || RS.NOME
         || ' SALARIO: ' || RS.SALARY);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('FIM DO PROCESSAMENTO');
    RETURN 0;
END;

-- Transformar em function
CREATE OR REPLACE FUNCTION FUNC_TESTE (P_IDDEPARTAMENTO IN EMPLOYEES.DEPARTMENT_ID%TYPE) 
    RETURN NUMBER
IS
BEGIN
    FOR RS IN (
        SELECT EMPLOYEE_ID, FIRST_NAME NOME, LAST_NAME AS SOBRENOME, SALARY,
               SALARY * 2 SALARIO_MULTIPLICADO
          FROM EMPLOYEES
         WHERE DEPARTMENT_ID = V_IDDEPT
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE('NOME DO FUNCIONARIO: ' || RS.NOME
         || ' SALARIO: ' || RS.SALARY);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('FIM DO PROCESSAMENTO');
    RETURN 0;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN SQLCODE;
END;
/

DECLARE
    RET NUMBER;
BEGIN
    RET := FUNC_TESTE(60);
    DBMS_OUTPUT.PUT_LINE('Retorno: ' || RET);
END;
