DECLARE
    IDADE NUMBER(3);
    V_SALARIO NUMBER(10,2) := 1000;
    V_NOME VARCHAR2(120);
BEGIN
    IDADE := 35;
    IDADE := IDADE * 2;
    V_NOME := 'MARIA';
    V_SALARIO := IDADE;

    DBMS_OUTPUT.PUT_LINE('A IDADE É: ' || idade);
    DBMS_OUTPUT.PUT_LINE('NOME: ' || idade);
END;
--------------------------------------
DECLARE
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    V_EMPLOYEE_ID := 105;
    SELECT FIRST_NAME INTO V_FIRST_NAME
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;

    DBMS_OUTPUT.PUT_LINE('O NOME DO FUNCIONÁRIO É: ' || V_FIRST_NAME);
END;
-----------------------
DECLARE --(mais complexo)
    V_DEPARTMENT_ID DEPARTMENTS.DEPARTMENT_ID%TYPE;
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
    CONTADOR NUMBER;
BEGIN
    V_DEPARTMENT_ID := 60;
 
    SELECT COUNT(*) INTO CONTADOR
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = V_DEPARTMENT_ID;
 
    IF CONTADOR>0 THEN
        SELECT DEPARTMENT_NAME
        INTO V_DEPARTMENT_NAME
        FROM DEPARTMENTS
        WHERE DEPARTMENT_ID = V_DEPARTMENT_ID;
 
         DBMS_OUTPUT.PUT_LINE('O NOME DO DEPARTAMENTO É ' || V_DEPARTMENT_NAME);
         DBMS_OUTPUT.PUT_LINE('CONTADOR: ' || CONTADOR);
    END IF;
END;
 
DECLARE  --(mais simples):
    V_DEPARTMENT_ID DEPARTMENTS.DEPARTMENT_ID%TYPE;
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    V_DEPARTMENT_ID := 10;
 
    SELECT DEPARTMENT_NAME
    INTO V_DEPARTMENT_NAME
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = V_DEPARTMENT_ID;
 
    DBMS_OUTPUT.PUT_LINE('O NOME DO DEPARTAMENTO É ' || V_DEPARTMENT_NAME);
END;
--------------------------------------
DECLARE
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_DEPARTMENT EMPLOYEES.V_DEPARTMENT_ID%TYPE;
BEGIN
    V_EMPLOYEE_ID := 105;
    SELECT FIRST_NAME INTO V_FIRST_NAME
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
    V_DEPARTMENT_ID := 1;

    SELECT DEPARTMENT_NAME INTO V_DEPARTMENT_NAME
    FROM DEPARTMENTS 
    WHERE DEPARTMENT_ID INTO = V_DEPARTMENT_ID;

    DBMS_OUTPUT.PUT_LINE('O NOME DO FUNCIONARIO É: ' || V_FUNCIONARIO_ID);
    DBMS_OUTPUT.PUT_LINE('O NOME DO DEPARTAMENTO É: ' || V_DEPARTMENT_ID);
    
    DBMS_OUTPUT.PUT_LINE('O NOME DO FUNCIONÁRIO É: ' || V_FIRST_NAME
    );
END;
--------------------------------------
SELECT FIRST_NAME, DEPARTMENT_NAME INTO V_FIRST_NAME, Y_DEPARTMENT_NAME
FROM EMPLOYEES EMP
LEFT JOIN DEPARTAMENTS DEP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
--------------------------------------
DECLARE
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    V_EMPLOYEE_ID := 105;
 
    SELECT EMP.FIRST_NAME, DEP.DEPARTMENT_NAME
    INTO V_FIRST_NAME, V_DEPARTMENT_NAME
    FROM EMPLOYEES EMP
    LEFT JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
    WHERE EMP.EMPLOYEE_ID = V_EMPLOYEE_ID;
 
    DBMS_OUTPUT.PUT_LINE('O NOME DO FUNCIONÁRIO É: ' || V_FIRST_NAME || ' E O DO DEPARTAMENTO É: ' || V_DEPARTMENT_NAME);
 
    IF V_DEPARTMENT_NAME = 'IT' THEN
        V_DEPARTMENT_NAME := 'TECNOLOGIA DA INFORMAÇÃO';
    ELSE
        V_DEPARTMENT_NAME := V_DEPARTMENT_NAME;
    END IF;
 
    DBMS_OUTPUT.PUT_LINE('O NOME DO DEPARTAMENTO É: ' || V_DEPARTMENT_NAME);
END;
