DROP TABLE MATRICULA;
DROP TABLE PROFESSOR;
DROP TABLE TITULACAO;
DROP TABLE ALUNO;
DROP TABLE DISCIPLINA;
 
CREATE TABLE TITULACAO(
    ID_TIT NUMBER(4) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    CONSTRAINT UQ_TIT_NOME UNIQUE (NOME)
);
 
CREATE TABLE PROFESSOR(
  ID_PROF NUMBER(4) PRIMARY KEY,
  NOME VARCHAR2(120) NOT NULL,
  GENERO CHAR(1) NOT NULL,
  ATIVO CHAR(1) NOT NULL,
  ID_TIT NUMBER(4) NOT NULL,
  CONSTRAINT CK_PROF_ATIVO CHECK (ATIVO IN ('S', 'N')),
  CONSTRAINT CK_PROF_GENERO CHECK (GENERO IN ('M', 'F')),
  CONSTRAINT FK_TIT_PROF FOREIGN KEY (ID_TIT)
             REFERENCES TITULACAO (ID_TIT)
);
 
CREATE TABLE ALUNO(
  RA NUMBER(8) PRIMARY KEY,
  NOME VARCHAR2(120) NOT NULL,
  GENERO CHAR(1) NOT NULL,
  ATIVO CHAR(1) NOT NULL,
  CONSTRAINT CK_ALU_ATIVO CHECK (ATIVO IN ('S', 'N')),
  CONSTRAINT CK_ALU_GENERO CHECK (GENERO IN ('M', 'F'))
);
 
CREATE TABLE DISCIPLINA(
  ID_DISC NUMBER(4) PRIMARY KEY,
  NOME VARCHAR2(120) NOT NULL,
  CARGA_HORARIA NUMBER(3) NOT NULL,
  CONSTRAINT UQ_DISC_NOME UNIQUE (NOME)
);
 
CREATE TABLE MATRICULA(
  RA NUMBER(8),
  ID_PROF NUMBER(4),
  ID_DISC NUMBER(4),
  ANO_SEM NUMBER(5),
  MEDIA NUMBER(4,2),
  FREQUENCIA NUMBER(5,2),
  CONSTRAINT PK_MATRICULA PRIMARY KEY (RA, ID_PROF, ID_DISC, ANO_SEM),
  CONSTRAINT FK_MAT_ALU FOREIGN KEY (RA)
                REFERENCES ALUNO (RA),
  CONSTRAINT FK_MAT_PROF FOREIGN KEY (ID_PROF)
                REFERENCES PROFESSOR (ID_PROF),
  CONSTRAINT FK_MAT_DISC FOREIGN KEY (ID_DISC)
                REFERENCES DISCIPLINA (ID_DISC)
);