-- DROP TABLE PRODUTO;
-- DROP TABLE TIPO_PRODUTO;

-- Criação de tabelas (CREATES)
CREATE TABLE TIPO_PRODUTO (
    id NUMBER(2) PRIMARY KEY,
    nome VARCHAR2(120) NOT NULL,
    CONSTRAINT UQ_TPPROD_NOME UNIQUE (NOME)
);

CREATE TABLE PRODUTO (
    id NUMBER(3) NOT NULL,
    nome VARCHAR2(120) NOT NULL,
    preco_venda NUMBER(8,2) NOT NULL,
    preco_compra NUMBER(9,2) NOT NULL,
    descricao VARCHAR2(4000) NULL,
    estoque NUMBER(5) NOT NULL,
    ativo CHAR(1) NOT NULL,
    dth_ultima_compra DATE NULL,
    id_tp NUMBER(2),
    CONSTRAINT PK_PROD PRIMARY KEY (ID),
    CONSTRAINT UQ_PROD_NOME UNIQUE (NOME),
    CONSTRAINT CK_PRO_ATIVO CHECK (ATIVO IN ('S', 'N')),
    CONSTRAINT FK_PROD_TP FOREIGN KEY (ID_TP) REFERENCES TIPO_PRODUTO(ID)
);

-- Inserção de dados (INSERTS)
INSERT INTO PRODUTO (ID, NOME, PRECO_VENDA, PRECO_COMPRA, DESCRICAO, ESTOQUE, ATIVO, DTH_ULTIMA_COMPRA, ID_TP) 
VALUES (10, 'Caneta BIC', 1.32, 2, NULL, 120, 'S', TO_DATE('29/09/2025', 'DD/MM/YYYY'), NULL);

COMMIT;

SELECT * FROM PRODUTO;

INSERT INTO TIPO_PRODUTO (ID, NOME) 
VALUES (1, 'Papelaria');

CREATE SEQUENCE SEQ_PROD_TP
MINVALUE 1 -- START WITH 1
MAXVALUE 99
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO TIPO_PRODUTO (ID, NOME) VALUES (SEQ_PROD_TP.NEXTVAL, 'Material de Limpeza');
INSERT INTO TIPO_PRODUTO (ID, NOME) VALUES (SEQ_PROD_TP.NEXTVAL, 'Material Escritório');
INSERT INTO TIPO_PRODUTO (ID, NOME) VALUES (SEQ_PROD_TP.NEXTVAL, 'Material de Construção');

SELECT * FROM TIPO_PRODUTO;

COMMIT;

INSERT INTO PRODUTO (ID, NOME, PRECO_VENDA, PRECO_COMPRA, DESCRICAO, ESTOQUE, ATIVO, DTH_ULTIMA_COMPRA, ID_TP) 
VALUES (23, 'Martelo', 13.33, 26.50, 'Martelo Redondo', 10, 'S', TO_DATE('30/09/2025 17:05:08', 'DD/MM/YYYY HH24:MI:SS'), 3);

SELECT * FROM PRODUTO;

COMMIT;

UPDATE PRODUTO 
    SET PRECO_COMPRA = 14.80, 
    DTH_ULTIMA_COMPRA = TO_DATE('29/09/2025 15:30:00', 'DD/MM/YYYY HH24:MI:SS'), 
    ESTOQUE = 20 
WHERE ID = 22;

-- O PRODUTO DE CODIGO 10 DEVE SER CLASSIFICADO COMO TIPO DE PRODUTO DE ID TIPO DE PRODUTO IGUAL A 2
UPDATE PRODUTO
SET ID_TP = 2
WHERE ID = 10;

-- DEVIDO A NOVOS IMPOSTOS A EMPRESA PRECISA APLICAR UMA AUMENTO DE 5% NO VALOR DA VENDA DE TODOS OS PRODUTOS
UPDATE PRODUTO SET PRECO_VENDA = PRECO_VENDA + (PRECO_VENDA * 0.05);
SELECT ID, PRECO_VENDA, PRECO_VENDA + (PRECO_VENDA * 0.05) FROM PRODUTO;

/* CRIAR UMA NOVA CATEGORIA (TIPO DE PRODUTO) DENOMIDADA ESCRITÓRIO, COM CODIGO 12 TRANSFERIR TODOS OS PRODUTOS
QUE ESTÃO NA CATEGORIA MATERIAL DE ESCRITÓRIO PARA A NOVA CATEGORIA ESCRITÓRIO E AO FINAL APAGAR A CATEGORIA MATERIAL DE ESCRITÓRIO */
INSERT INTO TIPO_PRODUTO (ID, NOME) VALUES (12, 'Escritório');
UPDATE PRODUTO SET ID_TP = 12 WHERE ID_TP = 3;
DELETE FROM TIPO_PRODUTO WHERE ID = 2;

-- DELETE TODOS OS REGISTRO E DISTRUA TODAS AS TABELAS
DELETE FROM PRODUTO;
DELETE FROM TIPO_PRODUTO;
DROP TABLE PRODUTO;
DROP TABLE TIPO_PRODUTO;