DROP TABLE Cliente CASCADE CONSTRAINTS;
DROP TABLE Produto CASCADE CONSTRAINTS;
DROP TABLE Categoria CASCADE CONSTRAINTS;
DROP TABLE Produto_Categoria CASCADE CONSTRAINTS;
DROP TABLE Pedido CASCADE CONSTRAINTS;
DROP TABLE Item_Pedido CASCADE CONSTRAINTS;
DROP TABLE Pagamento CASCADE CONSTRAINTS;

-- Tabela Cliente
CREATE TABLE Cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(11) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    telefone VARCHAR2(15),
    endereco VARCHAR2(255)
);

-- Tabela Produto
CREATE TABLE Produto (
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    descricao CLOB, Q   
    preco NUMBER(10, 2) NOT NULL,
    estoque NUMBER NOT NULL
);

-- Tabela Categoria
CREATE TABLE Categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_categoria VARCHAR2(100) NOT NULL,
    descricao CLOB
);

-- Tabela Produto_Categoria (relacionamento N:N)
CREATE TABLE Produto_Categoria (
    id_produto NUMBER,
    id_categoria NUMBER,
    PRIMARY KEY (id_produto, id_categoria),
    FOREIGN KEY (id_produto) REFERENCES Produto(id_produto),
    FOREIGN KEY (id_categoria) REFERENCES Categoria(id_categoria)
);

-- Tabela Pedido
CREATE TABLE Pedido (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER,
    data_pedido DATE NOT NULL,
    valor_total NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente)
);

-- Tabela Item_Pedido
CREATE TABLE Item_Pedido (
    id_item NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido NUMBER,
    id_produto NUMBER,
    quantidade NUMBER NOT NULL,
    preco_unitario NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido),
    FOREIGN KEY (id_produto) REFERENCES Produto(id_produto)
);

-- Tabela Pagamento
CREATE TABLE Pagamento (
    id_pagamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido NUMBER,
    forma_pagamento VARCHAR2(50) NOT NULL,
    valor_pago NUMBER(10, 2) NOT NULL,
    data_pagamento DATE NOT NULL,
    FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido)
);
