DROP TABLE FUNCIONARIO_AQB_LOG;

CREATE TABLE FUNCIONARIO_AQB_LOG(
    ID_LOG NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER(6) NOT NULL,
    TIPO_OPERACAO CHAR(1) NOT NULL,
    SALARY_VELHO NUMBER(8,2) NULL,
    SALARY_NOVO NUMBER(8,2) NULL,
    USUARIO VARCHAR2(30) NOT NULL,
    DTH_REGISTRO DATE NOT NULL,
    SQL_VOLTA VARCHAR(4000) NOT NULL
);

DROP SEQUENCE SEQ_FUNCIONARIO_AQB_LOG;

CREATE SEQUENCE SEQ_FUNCIONARIO_AQB_LOG
NOCACHE
NOCYCLE;

DROP TRIGGER TRG_LOG_FUNCIONARIOS_AQB;

CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOS_AQB
BEFORE INSERT OR UPDATE OR DELETE
ON FUNCIONARIOS_AQB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
        VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, 'I', NULL, :NEW.SALARY, USER, SYSDATE, 'DELETE FROM FUNCIONARIOS_AQB WHERE EMPLOYEE_ID = ' || :NEW.EMPLOYEE_ID || ';');
    ELSIF UPDATING THEN
        INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
        VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, 'U', :OLD.SALARY, :NEW.SALARY, USER, SYSDATE, 'UPDATE FUNCIONARIOS_AQB SET SALARY = ' || :OLD.SALARY || ' WHERE EMPLOYEE_ID = ' || :NEW.EMPLOYEE_ID || ';');
    ELSIF DELETING THEN
        INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
        VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :OLD.EMPLOYEE_ID, 'D', :OLD.SALARY, NULL, USER, SYSDATE, 'INSERT INTO FUNCIONARIOS_AQB (EMPLOYEE_ID,
            FIRST_NAME,
            LAST_NAME,
            EMAIL,
            PHONE_NUMBER,
            HIRE_DATE,
            JOB_ID,
            SALARY,
            COMMISSION_PCT,
            MANAGER_ID,
            DEPARTMENT_ID) 
            VALUES ('
            || '''' || :OLD.EMPLOYEE_ID || ''', '
            || '''' || :OLD.FIRST_NAME || ''', '
            || '''' || :OLD.LAST_NAME || ''', '
            || '''' || :OLD.EMAIL || ''', '
            || '''' || :OLD.PHONE_NUMBER || ''', '
            || '''' || :OLD.HIRE_DATE || ''', '
            || '''' || :OLD.JOB_ID || ''', '
            || :OLD.SALARY || ', '
            || :OLD.COMMISSION_PCT || ', '
            || :OLD.MANAGER_ID || ', '
            || :OLD.DEPARTMENT_ID
            || ');'
            );
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOS_AQB
BEFORE DELETE OR INSERT OR UPDATE OF SALARY
ON FUNCIONARIOS_AQB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
                INSERT INTO FUNCIONARIO_AQB_LOG
                  (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
                  SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
            VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL,
            :NEW.EMPLOYEE_ID, :OLD.SALARY,
            :NEW.SALARY, USER, SYSDATE, 'I',
            'DELETE FROM FUNCIONARIOS_AQB WHERE EMPLOYEE_ID = ' || :NEW.EMPLOYEE_ID  || ';'
            );
    ELSIF UPDATING THEN
        INSERT INTO FUNCIONARIO_AQB_LOG
                  (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
                  SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
            VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL,
            :NEW.EMPLOYEE_ID, :OLD.SALARY,
            :NEW.SALARY, USER, SYSDATE, 'U',
'UPDATE FUNCIONARIO_AQB SET SALARY = ' || :OLD.SALARY || ' WHERE EMPLOYEE_ID = ' || :OLD.EMPLOYEE_ID || ';'
            );
    ELSIF DELETING THEN
        INSERT INTO FUNCIONARIO_AQB_LOG
          (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
          SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
    VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL,
    :OLD.EMPLOYEE_ID, :OLD.SALARY,
    :NEW.SALARY, USER, SYSDATE, 'D',
    'INSERT INTO FUNCIONARIOS_AQB '
    || ' (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES ('
    || TO_CHAR(:OLD.EMPLOYEE_ID) || ','
    || NVL2(:OLD.FIRST_NAME,   '''' || :OLD.FIRST_NAME || '''',  'NULL') || ','
    || NVL2(:OLD.LAST_NAME,    '''' || :OLD.LAST_NAME || '''',   'NULL') || ','
    || NVL2(:OLD.EMAIL,        '''' || :OLD.EMAIL || '''',       'NULL') || ','
    || NVL2(:OLD.PHONE_NUMBER, '''' || :OLD.PHONE_NUMBER || '''', 'NULL') || ','
    || NVL2(:OLD.HIRE_DATE,    'TO_DATE(''' || TO_CHAR(:OLD.HIRE_DATE, 'YYYY-MM-DD HH24:MI:SS') || ''',''YYYY-MM-DD HH24:MI:SS'')', 'NULL') || ','
    || NVL2(:OLD.JOB_ID,       '''' || :OLD.JOB_ID || '''',      'NULL') || ','
    || NVL2(:OLD.SALARY,     TO_CHAR(:OLD.SALARY), 'NULL')
    || NVL(REPLACE(TO_CHAR(:OLD.SALARY), ',', '.'), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.COMMISSION_PCT), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.MANAGER_ID), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.DEPARTMENT_ID), 'NULL')
    || ');'
    );
    END IF;
END;

DROP FUNCTION FUNC_AUMENTA_SALARIO_AQB;

CREATE OR REPLACE FUNCTION FUNC_AUMENTA_SALARIO_AQB(P_PERC IN NUMBER)
RETURN NUMBER
IS
    V_RETORNO NUMBER(5);
    V_NOVO_SALARIO EMPLOYEES.SALARY%TYPE;
    V_ERRO NUMBER;
    V_DESC_ERRO VARCHAR2(1000);
BEGIN
    IF P_PERC > 0 AND P_PERC <= 15 THEN
        FOR I IN (
            SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY FROM FUNCIONARIOS_AQB
            WHERE JOB_ID != 'AD_PRES' AND JOB_ID != 'AD_VP')
        LOOP
            IF I.SALARY < 10000 THEN
                V_NOVO_SALARIO := I.SALARY * (1 + P_PERC/100);
            ELSE
                V_NOVO_SALARIO := I.SALARY;
            END IF;
        END LOOP;
        V_RETORNO := 0;
    ELSE
        V_RETORNO := -1;
    END IF;
    COMMIT;
    RETURN V_RETORNO;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        V_ERRO := SQLCODE;
        V_DESC_ERRO := SQLERRM;

        INSERT INTO LOG_EXECUCAO
            (ID_LOG, ERRO, DESC_ERRO, LINHA_ERRO, NOME_CODIGO, PARAMETROS, DTH_ERRO, USUARIO, RESOLVIDO, DESC_RESOLVIDO)
        VALUES
            (SEQ_LOG_EXECUCAO.NEXTVAL, V_ERRO, V_DESC_ERRO, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 'FUNC_AUMENTA_SALARIO_AQB', 'P_PERC = ' || P_PERC, SYSDATE, USER, 'N', NULL);
        COMMIT;
    RETURN SQLCODE;
END;

DECLARE
    RETORNO NUMBER(5);
BEGIN
    RETORNO := FUNC_AUMENTA_SALARIO_AQB(10);
    DBMS_OUTPUT.PUT_LINE('RETORNO: ' || RETORNO);
END;

ALTER TABLE FUNCIONARIOS_AQB
MODIFY EMAIL VARCHAR2(50);

INSERT INTO FUNCIONARIOS_AQB 
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES 
(300, 'Maria', 'Oliveira', 'maria.oliveira@ex.com', '11999998888',
 TO_DATE('05/05/2026', 'DD/MM/YYYY'),
 'IT_PROG', 5000.00, 0.10, 103, 60);
UPDATE FUNCIONARIOS_AQB SET SALARY = 9500 WHERE EMPLOYEE_ID = 300;
COMMIT;

SELECT ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO,
TO_CHAR(DTH_REGISTRO, 'DD/MM/YYYY HH24:MI:SS'), USUARIO, SQL_VOLTA
FROM FUNCIONARIO_AQB_LOG
WHERE EMPLOYEE_ID = 300
ORDER BY DTH_REGISTRO DESC;

DELETE FROM FUNCIONARIOS_AQB WHERE EMPLOYEE_ID = 300;