DROP TABLE FUNCIONARIO_AQB_LOG;
CREATE TABLE FUNCIONARIO_AQB_LOG(
    ID_LOG NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER(6) NOT NULL,
    TIPO_OPERACAO CHAR(1) NOT NULL, --NOVO
    SALARY_VELHO NUMBER(8,2) NULL, --PERMITE NULL AGORA
    SALARY_NOVO NUMBER(8,2) NULL, --PERMITE NULL AGORA
    USUARIO VARCHAR2(30) NOT NULL,
    DTH_REGISTRO DATE NOT NULL
);
-----------------
CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOS_AQB
BEFORE INSERT OR UPDATE OR DELETE OF SALARY
ON FUNCIONARIOS_AQB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
      INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO)
          VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, 'I',:OLD.SALARY, :NEW.SALARY, USER, SYSDATE);
    ELSIF UPDATING THEN
      INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO)
          VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, 'U',:OLD.SALARY, :NEW.SALARY, USER, SYSDATE);
    ELSE --DELETING
      INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO)
          VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :OLD.EMPLOYEE_ID, 'D',:OLD.SALARY, :NEW.SALARY, USER, SYSDATE);
    END IF;
END;
/
DECLARE
    RETORNO NUMBER(5);
BEGIN
    RETORNO := FUNC_AUMENTA_SALARIO_AQB(10);
    DBMS_OUTPUT.PUT_LINE('RETORNO = ' || RETORNO);
END;
/
SELECT * FROM FUNCIONARIO_AQB_LOG WHERE EMPLOYEE_ID = 1001
/
UPDATE FUNCIONARIOS_AQB SET SALARY = 74500 WHERE EMPLOYEE_ID = 1001
/
DELETE FROM FUNCIONARIOS_AQB WHERE EMPLOYEE_ID = 1001
/
SELECT * FROM FUNCIONARIOS_AQB
/
--INSERT INTO FUNCIONARIOS_AQB VALUES(627, 'LUIS', '', '', 123.456.7897 1000)
INSERT INTO FUNCIONARIOS_AQB (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
) VALUES (
    1001,
    'Joao',
    'Silva',
    'JOAO.SILVA',
    '11999998888',
    TO_DATE('05/05/2026', 'DD/MM/YYYY'),
    'IT_PROG',
    5000.00,
    0.10,
    103,
    60
);
----------------------------------------------------------------------------------------------DESAFIO:
DROP TABLE FUNCIONARIO_AQB_LOG;
CREATE TABLE FUNCIONARIO_AQB_LOG(
    ID_LOG NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER(6) NOT NULL,
    TIPO_OPERACAO CHAR(1) NOT NULL, --NOVO
    SALARY_VELHO NUMBER(8,2) NULL, --PERMITE NULL AGORA
    SALARY_NOVO NUMBER(8,2) NULL, --PERMITE NULL AGORA
    USUARIO VARCHAR2(30) NOT NULL,
    DTH_REGISTRO DATE NOT NULL,
    SQL_VOLTA VARCHAR(4000) NOT NULL
);
/
CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOS_AQB
BEFORE INSERT OR UPDATE OR DELETE OF SALARY
ON FUNCIONARIOS_AQB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
      INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
          VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, 'I',:OLD.SALARY, :NEW.SALARY, USER, SYSDATE, 'DELETE FROM FUNCIONARIOS_AQB WHERE EMPLOYEE_ID = '||:NEW.EMPLOYEE_ID);
    ELSIF UPDATING THEN
      INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
          VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, 'U',:OLD.SALARY, :NEW.SALARY, USER, SYSDATE, 'UPDATE FUNCIONARIOS_AQB'); --TERMINAR
    ELSE --DELETING
      INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
          VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :OLD.EMPLOYEE_ID, 'D',:OLD.SALARY, :NEW.SALARY, USER, SYSDATE, 'INSERT INTO FUNCIONARIOS_AQB WHERE EMPLOYEE_ID = '||:OLD.EMPLOYEE_ID); --ESPECIFICAR O CAMPO?
    END IF;
END;
/

/*INSERT INTO FUNCIONARIOS_AQB (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
) VALUES (
    :OLD.EMPLOYEE_ID,
    :OLD.FIRST_NAME,
    :OLD.LAST_NAME,
    :OLD.EMAIL,
    :OLD.PHONE_NUMBER,
    TO_DATE('05/05/2026', 'DD/MM/YYYY'),
    'IT_PROG',
    5000.00,
    0.10,
    103,
    60
);*/
