DECLARE
    V_JOB_ID HR.JOBS.JOB_ID%TYPE;
    V_JOB_TITLE HR.JOBS.JOB_TITLE%TYPE;
BEGIN
    X:= 1;0;

    V_JOB_ID := 'AD_VP';

    SELECT JOB_TITLE INTO V_JOB_TITLE
    FROM JOBS
    WHERE JOB_ID = V_JOB_ID;

    DBMS_OUTPUT.PUT_LINE('O NOME DO CARGO: ' || V_JOB_TITLE);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('NÃO EXISTE CARGO COM ESSE CÓDIGO');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('CÓDIGO DO ERRO: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('DESCRICAO DO ERRO: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('LINHA DO ERRO: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;

DECLARE
    V_JOB_ID HR.JOBS.JOB_ID%TYPE;
    V_JOB_TITLE HR.JOBS.JOB_TITLE%TYPE;
    V_QTDE NUMBER(1);
BEGIN
    V_JOB_ID := 'ADX_VP';

    SELECT COUNT(*)
    FROM JOBS
    WHERE JOB_ID = V_JOB_ID;
    IF V_QTDE = 1 THEN
        SELECT JOB_TITLE INTO V_JOB_TITLE
        FROM JOBS
        WHERE JOB_ID = V_JOB_ID;
        DBMS_OUTPUT.PUT_LINE('O NOME DO CARGO: ' || V_JOB_TITLE);
    ELSE
        DBMS_OUTPUT.PUT_LINE('CARGO INEXISTENTE');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('CÓDIGO DO ERRO: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('DESCRICAO DO ERRO: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('LINHA DO ERRO: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;

CREATE OR REPLACE
PROCEDURE PROC_RETORNANOMECARGO (P_JOBID IN HR.JOBS.JOB_ID%TYPE,
                                P_JORTITLE OUT HR.JOBS.JOB_TITLE%TYPE,
                                P_SAIDA OUT NUMBER)
IS
    V_QTDE NUMBER(1);
BEGIN
    SELECT COUNT(*) INTO V_QTDE
    FROM JOBS
    WHERE JOB_ID = P_JOBID;
    IF V_QTDE = 1 THEN
        SELECT JOB_TITLE INTO P_JORTITLE
        FROM JOBS
        WHERE JOB_ID = P_JOBID;
        P_SAIDA := 0;
    ELSE
        P_SAIDA := -1; -- NÃO EXISTE CARGO
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_SAIDA := SQLCODE;
        DBMS_OUTPUT.PUT_LINE('CÓDIGO DO ERRO: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('DESCRICAO DO ERRO: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('LINHA DO ERRO: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;

DECLARE
    NOME_CARGO HR.JOBS.JOB_TITLE%TYPE;
    RETORNO NUMBER(5);
BEGIN
    PROC_RETORNANOMECARGO('AD_VP', NOME_CARGO, RETORNO);
    IF RETORNO = 0 THEN
        DBMS_OUTPUT.PUT_LINE('NOME CARGO: ' || NOME_CARGO);
    ELSIF RETORNO = -1 THEN
        DBMS_OUTPUT.PUT_LINE('NAO EXISTE CARGO COM ESSE ID');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ERRO DO EXCEPTION: ' || RETORNO);
    END IF;
END;


-- TESTE DA PROCEDURE
SET SERVEROUTPUT ON;

-- Limpa a tabela antes dos testes
BEGIN
    DELETE FROM PESSOA;
    COMMIT;
END;
/

-- TEST 1: Inserção válida (esperado P_SAIDA = 0)
DECLARE
    v_saida NUMBER;
BEGIN
    PROC_INSERIR_PESSOA(1, 'Fulano', 1000.00, v_saida);
    DBMS_OUTPUT.PUT_LINE('TEST 1 - INSERCAO VALIDA: P_SAIDA='||v_saida);
END;
/

-- TEST 2: Inserção duplicada (esperado P_SAIDA = -1)
DECLARE
    v_saida NUMBER;
BEGIN
    PROC_INSERIR_PESSOA(1, 'Fulano', 1000.00, v_saida);
    DBMS_OUTPUT.PUT_LINE('TEST 2 - ID_DUPLICADO: P_SAIDA='||v_saida);
END;
/

-- TEST 3: ID fora da faixa (0) (esperado P_SAIDA = -2)
DECLARE
    v_saida NUMBER;
BEGIN
    PROC_INSERIR_PESSOA(0, 'Teste', 100.00, v_saida);
    DBMS_OUTPUT.PUT_LINE('TEST 3 - ID_FORA_DA_FAIXA: P_SAIDA='||v_saida);
END;
/

-- TEST 4: Nome muito longo (61 caracteres) (esperado P_SAIDA = -3)
DECLARE
    v_saida NUMBER;
    v_nome VARCHAR2(100) := RPAD('A',61,'A');
BEGIN
    PROC_INSERIR_PESSOA(2, v_nome, 100.00, v_saida);
    DBMS_OUTPUT.PUT_LINE('TEST 4 - NOME_LONGO: P_SAIDA='||v_saida);
END;
/

-- TEST 5: Salário inválido (negativo) (esperado P_SAIDA = -4)
DECLARE
    v_saida NUMBER;
BEGIN
    PROC_INSERIR_PESSOA(3, 'Beltrano', -1, v_saida);
    DBMS_OUTPUT.PUT_LINE('TEST 5 - SALARIO_INVALIDO: P_SAIDA='||v_saida);
END;
/
