/* ATIVIDADE
a) Receber os valores para RA e NOME do novo aluno; 
b) Checar o parametro de entrada NOME de acordo com o tamanho do campo a ser utilizado na alteracao, retornando -999;
c) Verificar a existencia do RA na tabela e caso nao exista, retornar -998;
d) Caso o NOME do aluno seja alterado, retornar 0;
e) Diretiva EXCEPTION para retornar o valor do SQLCODE, caso aconteça uma exceção não tratada.
*/

CREATE TABLE ALUNO(
    RA NUMBER PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    COD_CURSO NUMBER(5) NOT NULL --FK
)

CREATE OR REPLACE FUNCTION FUNC_ATUALIZA_ALUNO(P_RA IN ALUNO.RA%TYPE, P_NOME IN ALUNO.NOME%TYPE)
RETURN NUMBER
IS
    V_RETORNO NUMBER(5);
    V_QTDE NUMBER(5);
BEGIN
    IF LENGTH(P_NOME) > 120 THEN
        SELECT COUNT(*) INTO V_QTDE FROM ALUNO WHERE RA = P_RA;
        IF V_QTDE = 0 THEN
            UPDATE ALUNO SET NOME = P_NOME WHERE RA = P_RA;
            V_RETORNO := 0; -- SUCESSO
        ELSE
            V_RETORNO := -998; -- RA/ALUNO NAO EXISTE
        END IF;
    ELSE
        V_RETORNO := -999; -- NOME MUITO GRANDE 
    END IF;
    COMMIT;
    RETURN V_RETORNO;
-- EXCEPTION
--     WHEN OTHERS THEN
--         ROLLBACK;
--         RETURN SQLCODE;
-- END;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        V_ERRO := SQLCODE;
        V_DESC_ERRO := SQLERRM;

        INSERT INTO LOG_EXECUCAO
            (ID_LOG, ERRO, DESC_ERRO, LINHA_ERRO, NOME_CODIGO, PARAMETROS, DTH_ERRO, USUARIO, RESOLVIDO, DESC_RESOLVIDO)
        VALUES
            (SEQ_LOG_EXECUCAO.NEXTVAL, V_ERRO, V_DESC_ERRO, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 'FUNC_ATUALIZA_ALUNO', 'P_RA = ' || P_RA || ', P_NOME = ' || P_NOME, SYSDATE, USER, 'N', NULL);
        COMMIT;
    RETURN SQLCODE;
END;


-- Outro modo:

-- a) Receber os valores para RA e NOME do novo aluno; 
CREATE OR REPLACE FUNCTION ATUALIZA_ALUNO(P_RA IN ALUNO.RA%TYPE, P_NOME IN ALUNO.NOME%TYPE)
RETURN NUMBER
IS
    V_RETORNO NUMBER(5);
BEGIN
    -- b) Checar o parametro de entrada NOME de acordo com o tamanho do campo a ser utilizado na alteracao, retornando -999;
    IF LENGTH(P_NOME) > 120 THEN
        RETURN -999;
    END IF;

    -- c) Verificar a existencia do RA na tabela e caso nao exista, retornar -998;
    SELECT COUNT(*) INTO V_RETORNO FROM ALUNO WHERE RA = P_RA;
    IF V_RETORNO = 0 THEN
        RETURN -998;
    END IF;  

    -- d) Caso o NOME do aluno seja alterado, retornar 0;
    UPDATE ALUNO SET NOME = P_NOME WHERE RA = P_RA;
    IF SQL%ROWCOUNT > 0 THEN
        RETURN 0;
    END IF;

    -- e) Diretiva EXCEPTION para retornar o valor do SQLCODE, caso aconteça uma exceção não tratada.
EXCEPTION
    WHEN OTHERS THEN
        RETURN SQLCODE;
END;

---------------------------------------------

DROP TABLE LOG_EXECUCAO;
CREATE TABLE LOG_EXECUCAO(
    ID_LOG NUMBER PRIMARY KEY,
    ERRO NUMBER NOT NULL,
    DESC_ERRO VARCHAR2(1000) NOT NULL,
    NOME_CODIGO VARCHAR2(30) NOT NULL,
    PARAMETROS VARCHAR2(1000) NULL,
    DTH_ERRO DATE NOT NULL,
    USUARIO VARCHAR2(30) NOT NULL,
    RESOLVIDO CHAR(1) NOT NULL,
    DESC_RESOLVIDO VARCHAR2(1000) NULL
)

DROP SEQUENCE SEQ_LOG_EXECUCAO;
CREATE SEQUENCE SEQ_LOG_EXECUCAO
NO CACHE
NO CYCLE;

CREATE OR REPLACE FUNCTION AUMENTA_SALARIO_AQB(P_PERC IN NUMBER)
RETURN NUMBER
IS
    V_RETORNO NUMBER(5);
    V_NOVO_SALARIO EMPLOYEES.SALARY%TYPE;
    V_ERRO NUMBER;
    V_DESC_ERRO VARCHAR2(1000);
BEGIN
    -- V_RETORNO := 12345; -- CAUSA EXCEÇÃO PARA TESTAR O LOG
    IF P_PERC > 0 AND P_PERC <= 15 THEN
        FOR I IN (
            SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY FROM FUNCIONARIOS_AQB
            WHERE JOB_ID != 'AD_PRES' AND JOB_ID != 'AD_VP')
        LOOP
            IF I.SALARY < 10000 THEN
            END IF;
            UPDATE FUNCIONARIOS_AQB SET SALARY = V_NOVO_SALARIO
                WHERE EMPLOYEE_ID = I.EMPLOYEE_ID;

            INSERT INTO FUNCIONARIOS_AQB_LOG 
                (ID_LOG, EMPLOYEE_ID, SALARY_ANTES, SALARY_DEPOIS, USUARIO, DTH_REGISTRO)
            VALUES
                (SEQ_FUNCIONARIOS_AQB_LOG.NEXTVAL, I.EMPLOYEE_ID, I.SALARY, V_NOVO_SALARIO, USER, SYSDATE);

        END LOOP;
        V_RETORNO := 0;
    ELSE
        V_RETORNO := -1;
    END IF;
    COMMIT;
    RETURN V_RETORNO;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        V_ERRO := SQLCODE;
        V_DESC_ERRO := SQLERRM;

        INSERT INTO LOG_EXECUCAO
            (ID_LOG, ERRO, DESC_ERRO, LINHA_ERRO, NOME_CODIGO, PARAMETROS, DTH_ERRO, USUARIO, RESOLVIDO, DESC_RESOLVIDO)
        VALUES
            (SEQ_LOG_EXECUCAO.NEXTVAL, V_ERRO, V_DESC_ERRO, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 'AUMENTA_SALARIO_AQB', 'P_PERC = ' || P_PERC, SYSDATE, USER, 'N', NULL);
            -- ALTERAR O NOME DA PROGRAMACAO (AUMENTA_SALARIO_AQB) E INCLUIR TODOS OS PARAMETROS
        COMMIT;
    RETURN SQLCODE; -- SE NAO FOR FUNCTION, REMOVER O RETURN
END;
