DROP TABLE PRODUTO_VENDA;
CREATE TABLE PRODUTO_VENDA(
    ID NUMBER(4) PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    PRECO_VENDA NUMBER(10,2) NULL,
    PRECO_MEDIO_COMPRA NUMBER(10,2) NOT NULL,
    ATIVO CHAR(1) NOT NULL,
    CONSTRAINT CK_ATIVO_PRODUTOVENDA CHECK (ATIVO IN('S', 'N'))
 
)
 
INSERT INTO PRODUTO_VENDA(ID, NOME, PRECO_VENDA, PRECO_MEDIO_COMPRA, ATIVO)
    VALUES(1, 'CANETA AZUL', NULL, 0.85, 'S');
/
INSERT INTO PRODUTO_VENDA(ID, NOME, PRECO_VENDA, PRECO_MEDIO_COMPRA, ATIVO)
    VALUES(2, 'APAGADOR', 1.35, 1, 'S');
/
INSERT INTO PRODUTO_VENDA(ID, NOME, PRECO_VENDA, PRECO_MEDIO_COMPRA, ATIVO)
    VALUES(3, 'CLIPS', 0.05, 0.01, 'N');
/
INSERT INTO PRODUTO_VENDA(ID, NOME, PRECO_VENDA, PRECO_MEDIO_COMPRA, ATIVO)
    VALUES(4, 'MARTELO', 12, 7, 'S');
/
/*CREATE OR REPLACE FUNC_CALCPRECOVENDA(P_PERC_MARGEM IN NUMBER)
RETURN NUMBER
IS
BEGIN
    IF P_PERC_MARGEM>0 AND P_PERC_MARGEM<=100 THEN
        FOR RS IN (SELECT ID, PRECO_VENDA, PRECO_MEDIO_COMPRA
                    FROM PRODUTO_VENDA WHERE ATIVO = 'S')
                    --PRECO MEDIO,
        LOOP
            DBMS_OUTPUT.PUT_LINE('ID:'||RS.ID);
            DBMS_OUTPUT.PUT_LINE('PRECO_VENDA:'||RS.PRECO_VENDA);
            DBMS_OUTPUT.PUT_LINE('PRECO_MEDIO_COMPRA:'||RS.PRECO_MEDIO_COMPRA);
            DBMS_OUTPUT.PUT_LINE('P_PERC_MARGEM:'||P_PERC_MARGEM);
            DBMS_OUTPUT.PUT_LINE('MONO PRECO VENDA:'||(RS.PRECO_MEDIO_COMPRA+(PRECO_MEDIO_COMPRA*(P_PERC_MARGEM/100))));
        END LOOP;
        RETURN 0;
    ELSE
        RETURN -1; --FORA DA FAIXA DO PERCENTUNTUAL DA MARGEM
    END IF;
 
    WHEN OTHERS THEN
        RETURN SQLCODE;
END;*/
/
CREATE OR REPLACE FUNCTION FUNC_CALCPRECOVENDA(P_PERC_MARGEM IN NUMBER)
RETURN NUMBER
IS
    V_NOVO_PRECO_VENDA PRODUTO_VENDA.PRECO_VENDA%TYPE;
BEGIN
    IF P_PERC_MARGEM>=20 AND P_PERC_MARGEM<=100 THEN
        FOR RS IN (SELECT ID, NVL(PRECO_VENDA, 0) PRECO_VENDA, PRECO_MEDIO_COMPRA
                    FROM PRODUTO_VENDA WHERE ATIVO = 'S')
                    --PRECO MEDIO,
        LOOP
            DBMS_OUTPUT.PUT_LINE('ID:'||RS.ID);
            DBMS_OUTPUT.PUT_LINE('PRECO_VENDA:'||RS.PRECO_VENDA);
            DBMS_OUTPUT.PUT_LINE('PRECO_MEDIO_COMPRA:'||RS.PRECO_MEDIO_COMPRA);
             DBMS_OUTPUT.PUT_LINE('P_PERC_MARGEM:'||P_PERC_MARGEM);
            DBMS_OUTPUT.PUT_LINE('MONO PRECO VENDA:'||(RS.PRECO_MEDIO_COMPRA+(RS.PRECO_MEDIO_COMPRA*(P_PERC_MARGEM/100))));
 
            V_NOVO_PRECO_VENDA := (RS.PRECO_MEDIO_COMPRA+(RS.PRECO_MEDIO_COMPRA*(P_PERC_MARGEM/100)));
 
            IF V_NOVO_PRECO_VENDA > RS.PRECO_VENDA THEN
                DBMS_OUTPUT.PUT_LINE('FAZER UPDATE');
                UPDATE PRODUTO_VENDA SET PRECO_VENDA = V_NOVO_PRECO_VENDA
                    WHERE  ID = RS.ID;
            END IF;
 
            DBMS_OUTPUT.PUT_LINE('-------------------------------------------------');
        END LOOP;
        COMMIT;
        RETURN 0;
    ELSE
        RETURN -1; --FORA DA FAIXA DO PERCENTUNTUAL DA MARGEM
    END IF;
 
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN SQLCODE;
END;
/
DECLARE
    RETORNO NUMBER(5);
BEGIN
    RETORNO := FUNC_CALCPRECOVENDA(20);
    DBMS_OUTPUT.PUT_LINE('DO CODIGO DA CHAMADA -> RETORNO = '||RETORNO);
END;
/
----------------------------------------------------------------------------------
--COPIA LINHAS E COLUNAS DAS TABELAS
CREATE TABLE FUNCIONARIOS_AQB AS (SELECT * FROM HR.EMPLOYEES);
 
--------------
/*CRIAR UMA FUNÇÃO QUE AUMENTE O SALARIO DOS FUNCIONARIOS,
ESSA FUNÇÃO DEVE TER COMO PARAMETRO DE ENTRADA O INDICE DE AUMENTO,
QUE DEVE ESTAR ENTRE 0 (MAIOR QUE ZERO) E 15 PERCENTUAIS (MENOR IGUAL).
TODOS OS FUNCIONARIOS DEVE TER O AUMENTO, MENOS O PR4EIDENTE E VICE-PRSIDENTE.
O TETO MÁXIMO DE SALÁRIO DE UM FUNCIONARIO DEVE SER 10.000, MAS SE JÁ GANHA MAISQUE OS 10.000 DEVE
FICAR COM O SALARIO ATUAL (QUE É MAIOR QUE 10.000), ACRESCIDO DO PERCENTUAL DE AUMENTO.*/
 
CREATE OR REPLACE FUNCTION AUMENTA_SALARIO_AQB(P_PERC IN NUMBER)
RETURN NUMBER
IS
    V_RETORNO NUMBER(5);
    V_NOVO_SALARIO EMPLOYEES.SALARY%TYPE;
BEGIN
    IF P_PERC > 0 AND P_PERC <= 15 THEN
        FOR I IN (SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY FROM FUNCIONARIOS_AQB WHERE JOB_ID != 'AD_PRES' AND JOB_ID != 'AD_VP')
        LOOP
            IF I.SALARY < 10000 THEN --AND I.DEPARTMENT_ID != ??? THEN --PROF DISSE P USAR O JOB_ID
                V_NOVO_SALARIO := (((P_PERC/100)*I.SALARY)+I.SALARY);
                UPDATE FUNCIONARIOS_AQB
                SET SALARY = V_NOVO_SALARIO
                WHERE EMPLOYEE_ID = I.EMPLOYEE_ID;
 
                V_RETORNO := 0; --SUCESSO
            ELSE
                V_RETORNO := -2; --SALARIO MAIOR OU IGUAL A 10000
            END IF;
        END LOOP;
    ELSE
        V_RETORNO := -1; --PERCENTUAL FORA DA FAIXA ACEITÁVEL        
    END IF;
    COMMIT;
    RETURN V_RETORNO;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN SQLCODE;
END;