DROP TABLE PESSOA;

CREATE TABLE PESSOA(
    ID NUMBER(3) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    SALARIO NUMBER(7,2) NOT NULL
);

INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (1, 'MARIA', 99999.99);

INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (2, 'PAULO', -99.99);

COMMIT;

SELECT * FROM PESSOA;

CREATE OR REPLACE TRIGGER TRG_VALIDA_PESSOA
BEFORE INSERT OR UPDATE OF SALARIO
ON PESSOA
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO <= 0 OR :NEW.SALARIO > 10000 THEN
        RAISE_APPLICATION_ERROR(-20000, 'SALÁRIO FORA DA FAIXA DE VALOR');
    END IF;
END;
/

INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (3, 'CLAUDIA', 99999.99);

INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (4, 'EVERTON', -99.99);

COMMIT;

SELECT * FROM PESSOA;

INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (5, 'LUIS', 1000);

COMMIT;
    ''
SELECT * FROM PESSOA WHERE ID = 5;

UPDATE PESSOA SET SALARIO = 2000 WHERE ID = 5;

---------------------------------------------

/* ATIVIDADE
Crie uma trigger que só permite entrar valores entre 0 e 10 na coluna media.
Faça inserts e updates na coluna para validar o código.
Adapte a trigger para aceitar números de 0 a 100 na coluna frequencia.
*/

DROP TABLE MEDIAS_ALUNO;

CREATE TABLE MEDIAS_ALUNO(
    RA NUMBER(7) PRIMARY KEY,
    MEDIA NUMBER(4,2) NOT NULL,
    FREQUENCIA NUMBER(5,2) NOT NULL
);

CREATE OR REPLACE TRIGGER TRG_VALIDA_MEDIA
BEFORE INSERT OR UPDATE OF MEDIA, FREQUENCIA
ON MEDIAS_ALUNO
FOR EACH ROW
BEGIN
    IF :NEW.MEDIA < 0 OR :NEW.MEDIA > 10 THEN
        RAISE_APPLICATION_ERROR(-20000, 'MÉDIA DEVE ESTAR ENTRE 0 E 10');
    END IF;
    IF :NEW.FREQUENCIA < 0 OR :NEW.FREQUENCIA > 100 THEN
        RAISE_APPLICATION_ERROR(-20001, 'FREQUÊNCIA DEVE ESTAR ENTRE 0 E 100');
    END IF;
END;
/



---------------------------------------------

DROP TABLE FUNCIONARIOS_AQB;

CREATE TABLE FUNCIONARIOS_AQB AS (SELECT * FROM EMPLOYEES);

DROP TABLE FUNCIONARIOS_AQB_LOG;

CREATE TABLE FUNCIONARIOS_AQB_LOG(
    ID_LOG NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER(6) NOT NULL,
    SALARY_ANTES NUMBER(8,2) NOT NULL,
    SALARY_DEPOIS NUMBER(8,2) NOT NULL,
    USUARIO VARCHAR2(30) NOT NULL,
    DTH_REGISTRO DATE NOT NULL
);

DROP SEQUENCE LOG_FUNCIONARIOS_AQB;

CREATE SEQUENCE SEQ_FUNCIONARIOS_AQB_LOG
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP TABLE LOG_EXECUCAO;

CREATE TABLE LOG_EXECUCAO(
    ID_LOG NUMBER PRIMARY KEY,
    ERRO NUMBER NOT NULL,
    DESC_ERRO VARCHAR2(1000) NOT NULL,
    LINHA_ERRO VARCHAR2(1000) NOT NULL,
    NOME_CODIGO VARCHAR2(30) NOT NULL,
    PARAMETROS VARCHAR2(1000) NOT NULL,
    DTH_ERRO DATE NOT NULL,
    USUARIO VARCHAR2(30) NOT NULL,
    RESOLVIDO CHAR(1) NOT NULL,
    DESC_RESOLVIDO VARCHAR2(1000)
);

DROP SEQUENCE SEQ_LOG_EXECUCAO;

CREATE SEQUENCE SEQ_LOG_EXECUCAO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP FUNCTION AUMENTA_SALARIO_AQB;

CREATE OR REPLACE FUNCTION FUNC_AUMENTA_SALARIO_AQB(P_PERC IN NUMBER)
RETURN NUMBER
IS
    V_RETORNO NUMBER(5);
    V_NOVO_SALARIO EMPLOYEES.SALARY%TYPE;
    V_ERRO NUMBER;
    V_DESC_ERRO VARCHAR2(1000);
BEGIN
    IF P_PERC > 0 AND P_PERC <= 15 THEN
        FOR I IN (
            SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY FROM FUNCIONARIOS_AQB
            WHERE JOB_ID != 'AD_PRES' AND JOB_ID != 'AD_VP')
        LOOP
            IF I.SALARY < 10000 THEN
                V_NOVO_SALARIO := I.SALARY * (1 + P_PERC/100);
            ELSE
                V_NOVO_SALARIO := I.SALARY;
            END IF;
        END LOOP;
        V_RETORNO := 0;
    ELSE
        V_RETORNO := -1;
    END IF;
    COMMIT;
    RETURN V_RETORNO;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        V_ERRO := SQLCODE;
        V_DESC_ERRO := SQLERRM;

        INSERT INTO LOG_EXECUCAO
            (ID_LOG, ERRO, DESC_ERRO, LINHA_ERRO, NOME_CODIGO, PARAMETROS, DTH_ERRO, USUARIO, RESOLVIDO, DESC_RESOLVIDO)
        VALUES
            (SEQ_LOG_EXECUCAO.NEXTVAL, V_ERRO, V_DESC_ERRO, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 'AUMENTA_SALARIO_AQB', 'P_PERC = ' || P_PERC, SYSDATE, USER, 'N', NULL);
        COMMIT;
    RETURN SQLCODE;
END;

DECLARE
    RETORNO NUMBER(5);
BEGIN
    RETORNO := FUNC_AUMENTA_SALARIO_AQB(10);
    DBMS_OUTPUT.PUT_LINE('RETORNO: ' || RETORNO);
END;

SELECT * FROM FUNCIONARIOS_AQB;

-- UPDATE PELO CLIENT NÃO REGISTRA LOG
UPDATE FUNCIONARIOS_AQB SET SALARY = 9500 WHERE EMPLOYEE_ID = 103;

COMMIT;

SELECT ID_LOG, EMPLOYEE_ID, SALARY_ANTES, SALARY_DEPOIS, 
TO_CHAR(DTH_REGISTRO, 'DD/MM/YYYY HH24:MI:SS'), USUARIO
FROM FUNCIONARIOS_AQB_LOG
ORDER BY DTH_REGISTRO DESC;

CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOS_AQB
BEFORE INSERT OR UPDATE OF SALARY
ON FUNCIONARIOS_AQB
FOR EACH ROW
BEGIN    
    INSERT INTO FUNCIONARIOS_AQB_LOG 
        (ID_LOG, EMPLOYEE_ID, SALARY_ANTES, SALARY_DEPOIS, USUARIO, DTH_REGISTRO)
    VALUES
        (SEQ_FUNCIONARIOS_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE);
END;
/
