DROP TABLE CONSULTA CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE ESPECIALIDADE CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;

CREATE TABLE PACIENTE(
    ID_PAC NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(240) NOT NULL,
    DATA_NASC DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    CPF CHAR(14),
    CONSTRAINT CK_GENERO_PAC CHECK (GENERO IN ('M', 'F')),
    CONSTRAINT UQ_PAC_CPF UNIQUE (CPF)
);

CREATE TABLE ESPECIALIDADE(
    ID_ESP NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    CONSTRAINT UQ_ESP_NOME UNIQUE (NOME)
);

CREATE TABLE MEDICO(
    CRM NUMBER(7) PRIMARY KEY,
    NOME VARCHAR2(240) NOT NULL,
    DATA_NASC DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    ID_ESP NUMBER(10),
    CONSTRAINT CK_MED_GENERO CHECK (GENERO IN ('M', 'F')),
    CONSTRAINT FK_MED_ESP FOREIGN KEY (ID_ESP)
        REFERENCES ESPECIALIDADE (ID_ESP)
);

CREATE TABLE CONSULTA(
    CRM NUMBER(7),
    ID_PAC NUMBER(10),
    DTH_AGENDAMENTO DATE NOT NULL,
    TIPO CHAR(1) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    OBSERVACAO VARCHAR2(512),
    CONSTRAINT PK_CONSULTA PRIMARY KEY(CRM, ID_PAC, DTH_AGENDAMENTO),
    CONSTRAINT FK_CON_MED FOREIGN KEY (CRM)
        REFERENCES MEDICO (CRM),
    CONSTRAINT FK_CON_PAC FOREIGN KEY (ID_PAC)
        REFERENCES PACIENTE (ID_PAC),
    CONSTRAINT CK_CON_TIPO CHECK (TIPO IN ('C', 'R')),
    CONSTRAINT CK_CON_STATUS CHECK (STATUS IN ('A', 'C', 'R'))
);

INSERT INTO PACIENTE(ID_PAC, NOME, DATA_NASC, GENERO, CPF)
VALUES(1001, 'João Pedro', TO_DATE('05/06/1998', 'DD/MM/YYYY'), 'M', NULL);

INSERT INTO PACIENTE(ID_PAC, NOME, DATA_NASC, GENERO, CPF)
VALUES(1002, 'Ana Laura', TO_DATE('30/01/2003', 'DD/MM/YYYY'), 'F', '111.111.111-11');

INSERT INTO ESPECIALIDADE (ID_ESP, NOME)
VALUES(1, 'Cardiologista');

INSERT INTO MEDICO (CRM, NOME, DATA_NASC, GENERO, ID_ESP)
VALUES (2222, 'Carlos Eduardo', TO_DATE('10/09/1951', 'DD/MM/YYYY'), 'M', 1);