-- Visualizar a tabela JOBS
SELECT * FROM JOBS;

-- Visualizar a tabela EMPLOYEES (apenas algumas colunas)
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID 
FROM EMPLOYEES;

-- INNER JOIN implícito (vírgula no FROM + condição no WHERE)
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_TITLE
FROM EMPLOYEES, JOBS
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_ID;

-- INNER JOIN implícito com aliases e renome de colunas
SELECT EMPLOYEE_ID AS "CÓDIGO", EMP.FIRST_NAME AS NOME, JOB_TITLE
FROM EMPLOYEES EMP, JOBS JOB
WHERE EMP.JOB_ID = JOB.JOB_ID;

-- INNER JOIN implícito EMPLOYEES × DEPARTMENTS
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME
FROM EMPLOYEES EMP, DEPARTMENTS DEP
WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID;

-- LEFT OUTER JOIN na sintaxe antiga do Oracle (operador (+)); preserva EMP e DEP pode ser nulo
SELECT EMP.FIRST_NAME, EMP.EMPLOYEE_ID, DEP.DEPARTMENT_NAME
FROM EMPLOYEES EMP, DEPARTMENTS DEP
WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID(+);

-- 3 tabelas: EMP LEFT OUTER JOIN DEP (com (+)) + INNER JOIN JOBS (implícito)
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME, JOB.JOB_TITLE
FROM EMPLOYEES EMP, DEPARTMENTS DEP, JOBS JOB
WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID(+)
AND EMP.JOB_ID = JOB.JOB_ID;

-- RIGHT JOIN (este FROM traz todos os EMPREGADOS; para todos os DEPARTAMENTOS use DEP LEFT JOIN EMP ou EMP RIGHT JOIN DEP). Não misturar (+) com ANSI.
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME
FROM DEPARTMENTS DEP
RIGHT JOIN EMPLOYEES EMP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID(+);

-- INNER JOIN (forma moderna e mais legível)
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, JOB.JOB_TITLE
FROM EMPLOYEES EMP
INNER JOIN JOBS JOB
ON EMP.JOB_ID = JOB.JOB_ID;

-- LEFT JOIN em DEPARTMENTS e INNER JOIN em JOBS (sintaxe ANSI)
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME, JOB.JOB_TITLE
FROM EMPLOYEES EMP
LEFT JOIN DEPARTMENTS DEP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
INNER JOIN JOBS JOB
ON EMP.JOB_ID = JOB.JOB_ID;

-- Consulta final (ANSI): EMPLOYEES + DEPARTMENTS + JOBS + LOCATIONS
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME, JOB.JOB_TITLE, LOC.CITY
FROM EMPLOYEES EMP
LEFT JOIN DEPARTMENTS DEP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
LEFT JOIN JOBS JOB
ON EMP.JOB_ID = JOB.JOB_ID
LEFT JOIN LOCATIONS LOC
ON DEP.LOCATION_ID = LOC.LOCATION_ID;