DROP SEQUENCE SEQ_PACIENTE;
DROP SEQUENCE SEQ_ESPECIALIDADE;

CREATE SEQUENCE SEQ_PACIENTE
START WITH 1
MAXVALUE 9999999999 INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_ESPECIALIDADE
START WITH 10
MAXVALUE 9999 INCREMENT BY 10
NOCYCLE
NOCACHE;

INSERT INTO ESPECIALIDADE(ID_ESP, NOME) 
VALUES(SEQ_ESPECIALIDADE.NEXTVAL, 'CARDIOLOGISTA');

INSERT INTO ESPECIALIDADE(ID_ESP, NOME) 
VALUES(SEQ_ESPECIALIDADE.NEXTVAL, 'NEUROLOGISTA');

SELECT * FROM ESPECIALIDADE;

SELECT SEQ_ESPECIALIDADE.NEXTVAL FROM DUAL;
SELECT SEQ_ESPECIALIDADE.CURRVAL FROM DUAL;

INSERT INTO PACIENTE (ID_PAC, NOME, GENERO, DATA_NASC, CPF)
VALUES(SEQ_PACIENTE.NEXTVAL, 'Cláudia Aparecida Souza', 'F', TO_DATE('20/03/1998', 'DD/MM/YYYY'), NULL);

-- Só funciona se o SEQ_ESPECIALIDADE.NEXTVAL gerou exatamente o valor 10
INSERT INTO MEDICO (CRM, NOME, GENERO, DATA_NASC, ID_ESP)
VALUES(10111, 'João Carlos Almeida', 'M', TO_DATE('01/09/1951', 'DD/MM/YYYY'), 10);

-- SEQ_ESPECIALIDADE.NEXTVAL ou CURRVAL da sequência usada ao inserir especialidades
INSERT INTO MEDICO (CRM, NOME, GENERO, DATA_NASC, ID_ESP)
VALUES(10111, 'João Carlos Almeida', 'M', TO_DATE('01/09/1951', 'DD/MM/YYYY'), SEQ_ESPECIALIDADE.CURRVAL);

SELECT * FROM ESPECIALIDADE;

SELECT * FROM PACIENTE;

INSERT INTO CONSULTA (CRM, ID_PAC, DTH_AGENDAMENTO, TIPO, STATUS, OBSERVACAO)
VALUES(10111, 1, TO_DATE('01/09/2025', 'DD/MM/YYYY'), 'C', 'A', NULL);

SELECT * FROM CONSULTA;

SELECT ID_PAC, NOME, DATA_NASC, TO_CHAR(DATA_NASC, 'DD/MM/YYYY - DY - MONTH - YEAR - D') FROM PACIENTE;

SELECT CRM, ID_PAC, TO_CHAR(DTH_AGENDAMENTO, 'DD/MM/YYYY HH24:MI:SS'),
TIPO, STATUS, OBSERVACAO
FROM CONSULTA;

UPDATE PACIENTE 
SET DATA_NASC = TO_DATE('11/11/2012', 'DD/MM/YYYY'), GENERO = 'F', NOME = NOME||' TESTE'
WHERE ID_PAC = 1;

ROLLBACK; -- Desfaz as alterações feitas na transação atual que ainda não foram confirmadas
COMMIT; -- Confirma as alterações feitas na transação atual permanentementeas

DELETE FROM ESPECIALIDADE WHERE ID_ESP = 20;